name: .NET

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    if: "!contains(toJSON(github.event.commits.*.message), '[skip-ci]')"

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore --configuration Release
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: DJMapHelper
          path: bin/Release/net452
      - name: Archive Release
        if: startsWith(github.ref, 'refs/tags/')        
        uses: thedoctor0/zip-release@master
        with:
          filename: DJMapHelper.zip
          directory: bin/Release/net452/
      - name: Release
        uses: marvinpinto/action-automatic-releases@latest
        if: startsWith(github.ref, 'refs/tags/')
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          files: DJMapHelper.zip